ci: fix running in tutor binary as OfficialPlugin
The "hooks" object is a reserved dict keyword in the OfficialPlugin v0
API. This causes the tutor binary to fail loading the plugin on "tutor
plugins enable mfe":

	Error applying action 'plugins:loaded:mfe': func=<bound method BasePlugin.__load of <tutor.plugins.v0.OfficialPlugin object at 0x7fd065920f10>> contexts=['plugins']'
	Error: Invalid hooks in plugin mfe. Expected dict, got <class 'module'>.